version: 2
jobs:
  build:
    working_directory: /work
    docker:
      - image: hseeberger/scala-sbt:8u212_2.12.8_1.2.8
        environment:
          CIRCLE_TEST_ARTIFACTS: /tmp/artifacts

    steps:
      - run: mkdir /work
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: sbt clean compile
      - run: sbt coverage test coverageReport scalastyle scalafmtSbtCheck
      - run: cp target/scala-2.12/scoverage-report/index.html $CIRCLE_TEST_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
