version: 2
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: hseeberger/scala-sbt:8u212_2.12.8_1.2.8
        environment:
          CIRCLE_TEST_ARTIFACTS: /tmp/artifacts

    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run: mkdir -p $CIRCLE_TEST_ARTIFACTS
      - run: rm -f ensime.sbt
      - run: sbt clean compile
      - run: sbt coverage test coverageReport scalastyle scalafmtSbtCheck
      - run: bash <(curl -s https://codecov.io/bash)
      - run: cp -r target/scala-2.12/scoverage-report/* $CIRCLE_TEST_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
